const ASSET_VERSION="v450",c=document.getElementById("world"),ctx=c.getContext("2d"),I={},D=["N","NE","E","SE","S","SW","W","NW"];
function L(k,f){let i=new Image;i.src=f+"?v="+ASSET_VERSION;I[k]=i}L("bg","garden_background.png");["tree","bush_green","bush_flowers","flower_bed","wheelbarrow","birdbath_pool","bench","lantern","gate_left","gate_right","mailbox","bin","bin_full"].forEach(n=>L(n,n+".png"));D.forEach(d=>{L("p"+d,"player_"+d+".png");L("t"+d,"truck_"+d+".png")});for(let i=1;i<=4;i++)L("l"+i,"leaf_0"+i+".png");
let running=false,paused=false,joy={x:0,y:0},p={x:720,y:590,d:"S"},leaves=[],scoreN=0,totalPoints=0,binN=0,emptiedN=0,truck={on:false,x:-250,y:840,d:"E",t:0};
function spr(im,x,y,w,h){if(im?.complete&&im.naturalWidth)ctx.drawImage(im,x-w/2,y-h,w,h)}
function dir(x,y){if(Math.hypot(x,y)<.1)return p.d;let a=(Math.atan2(y,x)*180/Math.PI+360)%360;return D[Math.round((a+90)/45)%8]}
function reset(){scoreN=totalPoints=binN=emptiedN=0;p={x:720,y:590,d:"S"};leaves=Array.from({length:100},(_,i)=>({x:280+Math.random()*900,y:260+Math.random()*450,k:i%4+1,on:true}));ui()}
function ui(){leafCount.textContent=scoreN;score.textContent=totalPoints;binFill.textContent=binN;taskLeaves.textContent=totalPoints;taskBin.textContent=binN;empties.textContent=emptiedN;leafBar.style.width=Math.min(100,totalPoints)+"%";binBar.style.width=Math.min(100,binN)+"%"}
const fixed=[["bench",330,350,200,145],["wheelbarrow",850,355,185,140],["birdbath_pool",1010,320,175,115],["tree",1200,475,280,335],["bush_flowers",260,530,180,140],["bush_green",390,625,165,125],["lantern",220,590,85,170],["gate_left",810,830,180,205],["gate_right",1125,825,190,205],["mailbox",1245,745,85,135]];
function draw(){ctx.clearRect(0,0,1536,1024);if(I.bg?.complete)ctx.drawImage(I.bg,0,0,1536,1024);let q=[];fixed.forEach(o=>q.push({y:o[2],f:()=>spr(I[o[0]],o[1],o[2],o[3],o[4])}));leaves.forEach(l=>l.on&&q.push({y:l.y,f:()=>spr(I["l"+l.k],l.x,l.y,35,35)}));q.push({y:690,f:()=>spr(I[binN>=95?"bin_full":"bin"],1035,690,95,135)});q.push({y:p.y,f:()=>spr(I["p"+p.d],p.x,p.y,110,170)});if(truck.on)q.push({y:truck.y,f:()=>spr(I["t"+truck.d],truck.x,truck.y,290,190)});q.sort((a,b)=>a.y-b.y).forEach(o=>o.f())}
let last=performance.now();function loop(t){let dt=Math.min(.033,(t-last)/1000);last=t;if(running&&!paused)update(dt);draw();requestAnimationFrame(loop)}
function update(dt){if(Math.hypot(joy.x,joy.y)>.1){p.x=Math.max(80,Math.min(1450,p.x+joy.x*220*dt));p.y=Math.max(170,Math.min(910,p.y+joy.y*220*dt));p.d=dir(joy.x,joy.y)}leaves.forEach(l=>{if(l.on&&Math.hypot(l.x-p.x,l.y-p.y)<38){l.on=false;scoreN++;totalPoints++;ui()}});if(Math.hypot(p.x-1035,p.y-690)<60&&scoreN){let n=Math.min(100-binN,scoreN);binN+=n;scoreN-=n;ui();if(binN>=100&&!truck.on)truck={on:true,x:-250,y:840,d:"E",t:0}}if(truck.on){truck.t+=dt;if(truck.t<4){let u=truck.t/4;truck.x=-250+u*1200;truck.y=850;truck.d="E"}else if(truck.t<6){truck.x=950;truck.d="NE";if(truck.t>5&&binN){binN=0;emptiedN++;ui()}}else if(truck.t<10){let u=(truck.t-6)/4;truck.x=950-u*1200;truck.d="W"}else truck.on=false}}
start.onclick=()=>{menu.classList.add("hidden");game.classList.remove("hidden");reset();running=true};menuBtn.onclick=()=>{running=false;game.classList.add("hidden");menu.classList.remove("hidden")};
const J=document.getElementById("joy"),S=document.getElementById("stick");let pid=null;function move(e){let r=J.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,m=Math.hypot(x,y),mx=52;if(m>mx){x=x/m*mx;y=y/m*mx}joy={x:x/mx,y:y/mx};S.style.transform=`translate(${x}px,${y}px)`}J.onpointerdown=e=>{pid=e.pointerId;J.setPointerCapture(pid);move(e)};J.onpointermove=e=>{if(e.pointerId===pid)move(e)};function end(e){if(e.pointerId!==pid)return;pid=null;joy={x:0,y:0};S.style.transform=""}J.onpointerup=end;J.onpointercancel=end;requestAnimationFrame(loop);
pause.onclick=()=>{paused=!paused;pause.innerHTML=(paused?"▶":"Ⅱ")+"<small>"+(paused?"WEITER":"PAUSE")+"</small>"};
